package frontend;


import frontend.Token;
import backend.*;
import intermediate.*;
import frontend.*;

public class  Parser 
{
	private static SymbolTable symbolTable;  // generated symbol table
    private Scanner scanner;               // scanner used with this parser
    private IntermediateCode iCode;      // intermediate code generated by this parser

    /**
     * Constructor.
     * @param scanner the scanner to be used with this parser.
     */
    public Parser(Scanner bScanner)
    {
        scanner = bScanner;
    }
    
    
    public Token nextToken() throws Exception
    {
    	return scanner.nextToken();
    }
    
    
//Bob is soup
}
